import Head from 'next/head'
import { Inter } from '@next/font/google'
import { BsMicMuteFill } from 'react-icons/bs';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col justify-items-center items-center'>
        <div className='flex flex-col m-10 gap-4'>
          <div>
            俺はスーパーマンじゃねぇから世界中の人を守るなんてデケーことは言えねぇけど<br/>
            両手で抱えられるだけの人を守れればそれでいい。<br/>
            なんて言えるほど控えめな人間でもねぇんだ<br/>
            俺は山ほどの人を守りてぇんだ
          </div>
          <div>
            俺はスーパーマンじゃねぇから世界中の人を守るなんてデケーことは言えねぇけど<br/>
            両手で抱えられるだけの人を守れればそれでいい。<br/>
            なんて言えるほど控えめな人間でもねぇんだ<br/>
            俺は山ほどの人を守りてぇんだ
          </div>
        </div>
        <div className='fixed bottom-0 mb-10 text-4xl'>
          <BsMicMuteFill/>
        </div>
      </div>
    </div>
  )
}
