import Head from 'next/head'
import { Inter } from '@next/font/google'
import { BsMicMuteFill, BsMicFill } from 'react-icons/bs';
import React, { useState } from 'react';
import AudioReactRecorder, { RecordState } from 'audio-react-recorder'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isActive, setIsActive] = useState(false);
  const [recordState, setRecordState] = useState(null);

  const start = () => {
    setRecordState(RecordState.START)
  }

  const stop = () => {
    setRecordState(RecordState.STOP)
  }


  //audioData contains blob and blobUrl
  const onStop = (audioData: any) => {
    console.log('audioData', audioData)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col justify-items-center items-center'>
        <div className='flex flex-col m-10 gap-4'>
          <div>
            俺はスーパーマンじゃねぇから世界中の人を守るなんてデケーことは言えねぇけど<br/>
            両手で抱えられるだけの人を守れればそれでいい。<br/>
            なんて言えるほど控えめな人間でもねぇんだ<br/>
            俺は山ほどの人を守りてぇんだ
          </div>
        </div>
        
        <div>
          <AudioReactRecorder state={recordState} onStop={onStop} />

          <button onClick={start}>Start</button>
          <button onClick={stop}>Stop</button>
        </div>
        <div className='fixed bottom-0 mb-10 text-4xl'>
        {isActive? <BsMicFill onClick={()=>{
          setIsActive(!isActive)}}/>:
          <BsMicMuteFill onClick={()=>{
            setIsActive(!isActive)}} />
        }
        </div>
      </div>
    </div>
  )
}
